language: go
go:
  - 1.13.4

sudo: true

before_install:
  - curl -L  https://github.com/coreos/etcd/releases/download/v3.3.11/etcd-v3.3.11-linux-amd64.tar.gz -o etcd-v3.3.11-linux-amd64.tar.gz
  - tar xzvf etcd-v3.3.11-linux-amd64.tar.gz
  - ./etcd-v3.3.11-linux-amd64/etcd &

script:
  - go test -v ./...

